<?php

return [

    // PARTSTRAIN - DEV
    // "myaccount" => "http://myaccount.partstrain.dev.usautoparts.com/myaccount/login/",
    // "checkout" => "http://checkout.partstrain.dev.usautoparts.com/checkout/",
    // "cart" => "http://cart.partstrain.dev.usautoparts.com/basket",
    // "savequote" => "http://cart.partstrain.dev.usautoparts.com/basket/savequote/",
    // "retrievequote" => "http://cart.partstrain.dev.usautoparts.com/basket/getquote/",
    // "alladdress" => "http://myaccount.partstrain.dev.usautoparts.com/myaccount/alladdress/",
    // "changepassword" => "http://myaccount.partstrain.dev.usautoparts.com/myaccount/changepassword/",
    // "getallvehicles" => "http://myaccount.partstrain.dev.usautoparts.com/myaccount/getallvehicles/",
    // "search" => "http://partstrain.dev.usautoparts.com/store/",
    // "feedback" => "http://partstrain.dev.usautoparts.com/feedback/index.php",
    // "rma" => "http://partstrain.dev.usautoparts.com/myaccount/rma/",
    // STAGING
    // "myaccount" => "https://migration.myaccount.partstrain.staging.usautoparts.com/myaccount/login/",
    // "checkout" => "https://migration.checkout.partstrain.staging.usautoparts.com/checkout/",
    // "cart" => "http://migration.cart.partstrain.staging.usautoparts.com/basket/",
    // "savequote" => "http://migration.cart.partstrain.staging.usautoparts.com/basket/savequote/",
    // "retrievequote" => "http://migration.cart.partstrain.staging.usautoparts.com/basket/getquote/",
    // "alladdress" => "https://migration.myaccount.partstrain.staging.usautoparts.com/myaccount/alladdress/",
    // "changepassword" => "https://migration.myaccount.partstrain.staging.usautoparts.com/myaccount/changepassword/",
    // "getallvehicles" => "https://migration.myaccount.partstrain.staging.usautoparts.com/myaccount/getallvehicles/",
    // "search" => "http://migration.partstrain.staging.usautoparts.com/store/",
    // "feedback" => "http://migration.partstrain.staging.usautoparts.com/feedback/index.php",
    // "rma" => "https://migration.myaccount.partstrain.staging.usautoparts.com/myaccount/rma/",
    // PREPROD
    // "myaccount" => "https://preprod.myaccount.partstrain.staging.usautoparts.com/myaccount/login/",
    // "checkout" => "https://preprod.checkout.partstrain.staging.usautoparts.com/checkout/",
    // "cart" => "http://preprod.cart.partstrain.staging.usautoparts.com/basket?ai=true",
    // "savequote" => "http://preprod.cart.partstrain.staging.usautoparts.com/basket/savequote/",
    // "retrievequote" => "http://preprod.cart.partstrain.staging.usautoparts.com/basket/getquote/",
    // "alladdress" => "https://preprod.myaccount.partstrain.staging.usautoparts.com/myaccount/alladdress/",
    // "changepassword" => "https://preprod.myaccount.partstrain.staging.usautoparts.com/myaccount/changepassword/",
    // "getallvehicles" => "https://preprod.myaccount.partstrain.staging.usautoparts.com/myaccount/getallvehicles/",
    // "search" => "http://preprod.partstrain.staging.usautoparts.com/store/",
    // "feedback" => "http://preprod.partstrain.staging.usautoparts.com/feedback/index.php?w=1680&h=1050&u=aHR0cCUzQSUyRiUyRnByZXByb2QucGFydHN0cmFpbi5zdGFnaW5nLnVzYXV0b3BhcnRzLmNvbSUyRg==",
    // "rma" => "https://preprod.myaccount.partstrain.staging.usautoparts.com/myaccount/rma/?x=27&y=7",
    // PRODUCTION
    // "myaccount" => "https://myaccount.partstrain.com/myaccount/login/",
    // "checkout" => "https://checkout.partstrain.com/checkout/",
    // "cart" => "http://cart.partstrain.com/basket/",
    // "savequote" => "http://cart.partstrain.com/basket/savequote/",
    // "retrievequote" => "http://cart.partstrain.com/basket/getquote/",
    // "alladdress" => "https://myaccount.partstrain.com/myaccount/alladdress/",
    // "changepassword" => "https://myaccount.partstrain.com/myaccount/changepassword/",
    // "getallvehicles" => "https://myaccount.partstrain.com/myaccount/getallvehicles/",
    // "search" => "http://www.partstrain.com/store/",
    // "feedback" => "http://www.partstrain.com/feedback/index.php?w=1680&h=1050&u=aHR0cCUzQSUyRiUyRnd3dy5wYXJ0c3RyYWluLmNvbSUyRg==",
    // "rma" => "https://myaccount.partstrain.com/myaccount/rma/?x=16&y=9",
    // Origin prod
    // "myaccount" => "https://origin-myaccount.partstrain.com/myaccount/login/",
    // "checkout" => "https://origin-checkout.partstrain.com/checkout/",
    // "cart" => "http://origin-cart.partstrain.com/basket/",
    // "savequote" => "http://origin-cart.partstrain.com/basket/savequote/",
    // "retrievequote" => "http://origin-cart.partstrain.com/basket/getquote/",
    // "alladdress" => "https://origin-myaccount.partstrain.com/myaccount/alladdress/",
    // "changepassword" => "https://origin-myaccount.partstrain.com/myaccount/changepassword/",
    // "getallvehicles" => "https://origin-myaccount.partstrain.com/myaccount/getallvehicles/",
    // "search" => "http://origin.www.partstrain.com/store/",
    // "feedback" => "http://origin.www.partstrain.com/feedback/index.php?w=1680&h=1050&u=aHR0cCUzQSUyRiUyRnd3dy5wYXJ0c3RyYWluLmNvbSUyRg==",
    // "rma" => "https://origin-myaccount.partstrain.com/myaccount/rma/?x=16&y=9",

    // CPO -dev
    // "search" => "http://canadapartsonline.staging.usautoparts.com/search/",
    // "feedback" => "http://canadapartsonline.staging.usautoparts.com/feedback",
    // "myaccount" => "https://canadapartsonline.staging.usautoparts.com/myaccount/login/",
    // "trackorder" => "https://canadapartsonline.staging.usautoparts.com/myaccount/trackorder/",
    // "retrievequote" => "http://canadapartsonline.staging.usautoparts.com/basket/getquote/",
    // "savequote" => "http://canadapartsonline.staging.usautoparts.com/basket/savequote",
    // "rma" => "http://canadapartsonline.staging.usautoparts.com/myaccount/rma/",
    // "checkout" => "https://canadapartsonline.staging.usautoparts.com/checkout/",
    // "changepassword" => "https://canadapartsonline.staging.usautoparts.com/myaccount/changepassword/",
    // "addaddress" => "https://canadapartsonline.staging.usautoparts.com/myaccount/addaddress/",
    // "getallvehicles" => "https://canadapartsonline.staging.usautoparts.com/myaccount/getallvehicles/",
    // "addpaymentoption" => "https://canadapartsonline.staging.usautoparts.com/myaccount/addpaymentoption/",
    // "contactus" => "http://canadapartsonline.staging.usautoparts.com/customer/email/",
    // CPO -origin
    // "search" => "http://cpofe01.canadapartsonline.com/search/",
    // "feedback" => "http://cpofe01.canadapartsonline.com/feedback",
    // "myaccount" => "http://cpofe01.canadapartsonline.com/myaccount/login/",
    // "trackorder" => "http://cpofe01.canadapartsonline.com/myaccount/trackorder/",
    // "retrievequote" => "http://cpofe01.canadapartsonline.com/basket/getquote/",
    // "savequote" => "http://cpofe01.canadapartsonline.com/basket/savequote/",
    // "rma" => "http://cpofe01.canadapartsonline.com/myaccount/rma/",
    // "checkout" => "http://cpofe01.canadapartsonline.com/checkout/",
    // "changepassword" => "http://cpofe01.canadapartsonline.com/myaccount/changepassword/",
    // "addaddress" => "http://cpofe01.canadapartsonline.com/myaccount/addaddress",
    // "getallvehicles" => "http://cpofe01.canadapartsonline.com/myaccount/getallvehicles/",
    // "addpaymentoption" => "https://cpofe01.canadapartsonline.com/myaccount/addpaymentoption/",
    // "contactus" => "http://cpofe01.canadapartsonline.com/customer/email",
    // CA.CP
    // "search" => "http://canada.carparts.staging.usautoparts.com/search/",
    // "feedback" => "http://canada.carparts.staging.usautoparts.com/feedback",
    // "myaccount" => "https://canada.carparts.staging.usautoparts.com/myaccount/login/",
    // "trackorder" => "https://canada.carparts.staging.usautoparts.com/myaccount/trackorder/",
    // "retrievequote" => "http://canada.carparts.staging.usautoparts.com/basket/getquote/",
    // "savequote" => "http://canada.carparts.staging.usautoparts.com/basket/savequote/",
    // "rma" => "http://canada.carparts.staging.usautoparts.com/myaccount/rma/",
    // "checkout" => "https://canada.carparts.staging.usautoparts.com/checkout/",
    // "changepassword" => "https://canada.carparts.staging.usautoparts.com/myaccount/changepassword/",
    // "addaddress" => "https://canada.carparts.staging.usautoparts.com/myaccount/addaddress",
    // "getallvehicles" => "https://canada.carparts.staging.usautoparts.com/myaccount/getallvehicles/",
    // "addpaymentoption" => "https://canada.carparts.staging.usautoparts.com/myaccount/addpaymentoption/",
    // "contactus" => "http://canadapartsonline.staging.usautoparts.com/customer/email/",
    // CA.CP -origin
    // "search" => "http://cafe01.carparts.com/search/",
    // "feedback" => "http://cafe01.carparts.com/feedback",
    // "myaccount" => "https://cafe01.carparts.com/myaccount/login/",
    // "trackorder" => "https://cafe01.carparts.com/myaccount/trackorder/",
    // "retrievequote" => "http://cafe01.carparts.com/basket/getquote/",
    // "savequote" => "http://cafe01.carparts.com/basket/savequote/",
    // "rma" => "https://cafe01.carparts.com/myaccount/rma/",
    // "checkout" => "https://cafe01.carparts.com/checkout/",
    // "changepassword" => "https://cafe01.carparts.com/myaccount/changepassword/",
    // "addaddress" => "https://cafe01.carparts.com/myaccount/addaddress",
    // "getallvehicles" => "https://cafe01.carparts.com/myaccount/getallvehicles/",
    // "addpaymentoption" => "https://cafe01.carparts.com/myaccount/addpaymentoption/",
    // "contactus" => "http://cafe01.carparts.com/customer/email",
    // CA.JCW
    // "search" => "http://canada.jcwhitney.staging.usautoparts.com/search/",
    // "feedback" => "http://canada.jcwhitney.staging.usautoparts.com/feedback",
    // "myaccount" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/login/",
    // "trackorder" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/trackorder/",
    // "retrievequote" => "http://canada.jcwhitney.staging.usautoparts.com/basket/getquote/",
    // "savequote" => "http://canada.jcwhitney.staging.usautoparts.com/basket/savequote",
    // "rma" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/rma/",
    // "checkout" => "http://canada.jcwhitney.staging.usautoparts.com/checkout/",
    // "changepassword" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/changepassword/",
    // "addaddress" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/addaddress",
    // "getallvehicles" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/getallvehicles/",
    // "addpaymentoption" => "http://canada.jcwhitney.staging.usautoparts.com/myaccount/addpaymentoption/",
    // "contactus" => "http://canada.jcwhitney.staging.usautoparts.com/customer/email/",
    // CA.JCW -origin
    // "search" => "http://cafe01.jcwhitney.com/search/",
    // "feedback" => "http://cafe01.jcwhitney.com/feedback",
    // "myaccount" => "http://cafe01.jcwhitney.com/myaccount/login/",
    // "trackorder" => "http://cafe01.jcwhitney.com/myaccount/trackorder/",
    // "retrievequote" => "http://cafe01.jcwhitney.com/basket/getquote/",
    // "savequote" => "http://cafe01.jcwhitney.com/basket/savequote/",
    // "rma" => "http://cafe01.jcwhitney.com/myaccount/rma/",
    // "checkout" => "http://cafe01.jcwhitney.com/checkout/",
    // "changepassword" => "http://cafe01.jcwhitney.com/myaccount/changepassword/",
    // "addaddress" => "http://cafe01.jcwhitney.com/myaccount/addaddress",
    // "getallvehicles" => "http://cafe01.jcwhitney.com/myaccount/getallvehicles/",
    // "addpaymentoption" => "https://cafe01.jcwhitney.com/myaccount/addpaymentoption/",
    // "contactus" => "http://cafe01.jcwhitney.com/customer/email",
    // CA.APW -origin
    "search" => "http://cafe01.autopartswarehouse.com/search/",
    "feedback" => "http://cafe01.autopartswarehouse.com/feedback",
    "myaccount" => "http://cafe01.autopartswarehouse.com/myaccount/login/",
    "trackorder" => "http://cafe01.autopartswarehouse.com/myaccount/trackorder/",
    "retrievequote" => "http://cafe01.autopartswarehouse.com/basket/getquote/",
    "savequote" => "http://cafe01.autopartswarehouse.com/basket/savequote/",
    "rma" => "http://cafe01.autopartswarehouse.com/myaccount/rma/",
    "checkout" => "http://cafe01.autopartswarehouse.com/checkout/",
    "changepassword" => "http://cafe01.autopartswarehouse.com/myaccount/changepassword/",
    "addaddress" => "http://cafe01.autopartswarehouse.com/myaccount/addaddress",
    "getallvehicles" => "http://cafe01.autopartswarehouse.com/myaccount/getallvehicles/",
    "addpaymentoption" => "https://cafe01.autopartswarehouse.com/myaccount/addpaymentoption/",
    "contactus" => "http://cafe01.autopartswarehouse.com/customer/email",












];
